apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: webserver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
