apiVersion: v1
kind: Namespace
metadata:
  name: lab
  labels:
    name: lab
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: lab-b
  namespace: lab
spec:
  podSelector:
    matchLabels:
      app: lab-b
  ingress: []