apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lab-c
  namespace: lab
spec:
  rules:
  - host: "lab-c.example.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lab-c
            port:
              number: 443