apiVersion: apps/v1
kind: Deployment
metadata:
  name: validating-webhook
  namespace: webhook-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validating-webhook
  template:
    metadata:
      labels:
        app: validating-webhook
    spec:
      containers:
      - name: webhook
        image: derekdemo/lab-1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 1
            scheme: HTTPS
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: validating-webhook-svc
  namespace: webhook-system
spec:
  selector:
    app: some-webhook
  ports:
  - port: 443
    targetPort: 443
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-config
webhooks:
- name: validating.webhook.example.com
  clientConfig:
    service:
      name: validating-webhook-svc
      namespace: webhook-system
      path: "/always-allow-delay-5s"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUROakNDQWg2Z0F3SUJBZ0lVQ2hLWndYemFwYXExY1RqTmJ4cjRYQmxpL2RNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0VqRVFNQTRHQTFVRUF3d0hkR1Z6ZEMxallUQWdGdzB5TkRBNU16QXlNelV5TlRsYUdBOHlNRFV5TURJeApOakl6TlRJMU9Wb3dFakVRTUE0R0ExVUVBd3dIZEdWemRDMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFECmdnRVBBRENDQVFvQ2dnRUJBSmN2aGtWUnZEN1E5NlM2a0Q3b3JNaFhRcitsQzlJSVBaWVZyNm4xQVV6Tld0N08KWk56QWxuL0xCd211ckZVK2krcDhiYk13T2hFcXRQYUJmR2NMbTRUOGNpbkVzMDZmYzJEekpmZCtmNDdOZFhiUQo3QXl4NjZIYkFtRkMxeGF2NVpLSFNvM3BrTE1Xdk5SczZRREp4amd5ZkdGS3VmOXozbHFWb3RPYTBmOHNKYmpNCmVpT0lsS1BINndlOTM5bHlEVFc0TE9YQUwvRnBBY1gvN1BGNVlwOVZnM3VOZFgwUUFrNTVudzdZNUhReDRJZm8KVk4rOElMNGdHckZKb2ZCVWsxUkR1Z3ZsRHFWalk1NXgvSjltUVRFY2MwK0hhbG1sWFVrd3lSYTJPcGU2bWNUZgpQTndReklVWnEwb2hzNGVvcW1xRmFyd0FQTVBJU2txQ05UeGJRTDBDQXdFQUFhT0JnVEIvTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZQdXlHTE52MjNaa2dmTy9iVGFCUXpHREpxMHdNRTBHQTFVZEl3UkcKTUVTQUZQdXlHTE52MjNaa2dmTy9iVGFCUXpHREpxMHdvUmFrRkRBU01SQXdEZ1lEVlFRRERBZDBaWE4wTFdOaApnaFFLRXBuQmZOcWxxclZ4T00xdkd2aGNHV0w5MHpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQUsxUU9YZ3VJClIzNnNvYWFvbnJKcTR2My9jcXlVZzlUUTlPRDJGQ0NnNE0rRURWNFh4bXJrb0ErWm9xM0ZRai9CbDA5NHRGNmwKUVFzQnhrbHJtbmRIQnFucFo1SGdnczkzc0xUSVNMejUxUW5rcTNnRTBrb2hERWd1U1VGaXVNZzhybkJIeVJ5Rwp5TFgzYzNTdGR0N2Y4cnlxbXo4a3RoTFQ2eEwrMzdscHNaNVoraUFRb1RRZ2lpS0VRcWwydlkxOVBEZlFDMXNoCk9zSXFOMWJrQ3hEQkNkOW4vNXpGcEV2UEN6dUpFa0FjYmRRU0VheUNDOWY4MHR0OXNiOGZUTE91d1JtNEJ2OVEKT0NlNjFJZWVnZng1RU45cThMMWpQQTJaalZzaFlZMHc5OUdRVDJEakJvQ1RpbUoxWGJrcXVhelhrSi8yT1QyRgpVNHMvQldGZGIzcFNMdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
  rules:
  - apiGroups: ["*"]
    apiVersions: ["*"]
    operations: ["CREATE", "UPDATE", "DELETE"]
    resources: ["*"]
    scope: "Namespaced"
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: deployment-lab
  failurePolicy: Fail
  sideEffects: None
  admissionReviewVersions: ["v1"]
  timeoutSeconds: 10
