apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Default Page</title>
    </head>
    <body>
      <h1>Welcome to the Default Page</h1>
      <p>This page is served by a web server running in a Kubernetes cluster.</p>
    </body>
    </html>
